### ISSUE TITLE
ggplot lesson?

### ISSUE THREAD

**Issue by noamross** [datacarpentry/2015-02-09-ucdavis#3]
@tracykteal So there's currently a ggplot lesson in `R/r-ggplot2` that does not use the main data set.  Do we expect to use this or just the barplot stuff on day 2?

I note that D-RUG has a ggplot tutorial scheduled in a month.

**Comment by tracykteal** [comment]
Just the bar plot stuff on Day 2. That's great that there will be an upcoming ggplot tutorial. That will be the perfect follow on.
