### ISSUE TITLE
Lesson printouts

### ISSUE THREAD

**Issue by noamross** [datacarpentry/2015-02-09-ucdavis#5]
I am planning on printing out my lesson notes.  I could print them all out tomorrow morning before going the the library, if you'd like me to.

@tracykteal @michaellevy @erwhite1

**Comment by michaellevy** [comment]
@noamross that would save me a stop by my office in the morning, thanks!

**Comment by tracykteal** [comment]
Thanks @noamross. I'm still updating the shell ones so I'll print those tomorrow morning.
